/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Encriptador;

import com.google.api.core.ApiFuture;
import com.google.auth.oauth2.GoogleCredentials;
import com.google.cloud.firestore.DocumentReference;
import com.google.cloud.firestore.DocumentSnapshot;
import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.WriteResult;
import com.google.firebase.FirebaseApp;
import com.google.firebase.FirebaseOptions;
import com.google.firebase.cloud.FirestoreClient;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.math.BigInteger;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick
 */
public class EncriptadorPanel extends javax.swing.JFrame {

    /**
     * Creates new form EncriptadorPanel
     */
    public EncriptadorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NLabel = new javax.swing.JLabel();
        LabelE = new javax.swing.JLabel();
        ValorN = new javax.swing.JTextField();
        ValorE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MensajeArea = new javax.swing.JTextArea();
        EnviarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NLabel.setText("n=");

        LabelE.setText("e=");

        ValorN.setEditable(false);
        ValorN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorNActionPerformed(evt);
            }
        });

        ValorE.setEditable(false);
        ValorE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorEActionPerformed(evt);
            }
        });

        MensajeArea.setColumns(20);
        MensajeArea.setRows(5);
        jScrollPane1.setViewportView(MensajeArea);

        EnviarButton.setText("Enviar encriptado");
        EnviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ValorN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ValorE, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EnviarButton)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NLabel)
                    .addComponent(ValorN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelE)
                    .addComponent(ValorE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(EnviarButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValorNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorNActionPerformed

    private void ValorEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorEActionPerformed

    private void EnviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarButtonActionPerformed
        // TODO add your handling code here:
        DocumentReference docRef = db.collection("Llave Publica").document("Llave");
        // asynchronously retrieve the document
        ApiFuture<DocumentSnapshot> llave = docRef.get();
        // ...
        // future.get() blocks on response
        DocumentSnapshot document;
        try {
            document = llave.get();
            if (document.exists()) {
              Map<String,Object> llavePublica = document.getData();
              if(MensajeArea.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Texto vacio");
               }
              else if(llavePublica.get("e").toString().isEmpty()|| llavePublica.get("n").toString().isEmpty()){
                  JOptionPane.showMessageDialog(null, "llaves vacias");
                }
              else{
                  ValorE.setText(llavePublica.get("e").toString());
                  ValorN.setText(llavePublica.get("n").toString());
                  Encriptar= new Encriptador(new BigInteger(llavePublica.get("n").toString()),new BigInteger(llavePublica.get("e").toString()));
                  String Mensaje=MensajeArea.getText();
                  BigInteger[] MensajeEncriptado=Encriptar.encriptar(Mensaje);
                  docRef = db.collection("Mensajes").document("Mensaje");
                // Add document data  with id "alovelace" using a hashmap
                Map<String, Object> data = new HashMap<>();
                
                for(int i=0;i<MensajeEncriptado.length;i++){
                    data.put(""+i, MensajeEncriptado[i].toString());
                }
                data.put("Tamano", MensajeEncriptado.length);
                //asynchronously write data
                ApiFuture<WriteResult> result = docRef.set(data);
              }
            } else {
              System.out.println("No such document!");
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(EncriptadorPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExecutionException ex) {
            Logger.getLogger(EncriptadorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_EnviarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    private static Firestore db;
    private static Encriptador Encriptar;
    public static void main(String args[]) throws FileNotFoundException, IOException {
        FileInputStream serviceAccount =
          new FileInputStream("rsa-encriptacion-firebase-adminsdk-7ntfh-589f4a864a.json");

        FirebaseOptions options = new FirebaseOptions.Builder()
          .setCredentials(GoogleCredentials.fromStream(serviceAccount))
          .setDatabaseUrl("https://rsa-encriptacion.firebaseio.com")
          .build();

        FirebaseApp.initializeApp(options);
         db = FirestoreClient.getFirestore();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncriptadorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncriptadorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncriptadorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncriptadorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncriptadorPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnviarButton;
    private javax.swing.JLabel LabelE;
    private javax.swing.JTextArea MensajeArea;
    private javax.swing.JLabel NLabel;
    private javax.swing.JTextField ValorE;
    private javax.swing.JTextField ValorN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
